---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
  labels:
    app: server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: zcong/grpc-example:dns
          imagePullPolicy: IfNotPresent
          command:
            - server
            - -maxConnectionAge
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: headless-grpc-server
spec:
  clusterIP: None
  selector:
    app: server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: grpc-server
spec:
  selector:
    app: server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
